% Code generated by ChatGPT

% Set the size of the matrix
n = 32;

% Initialize the index array
idx = zeros(1,n^2);

% Compute the index array in diagonal zigzag order
index = 1;
for i = 1:n
    if mod(i,2) == 1
        for j = 1:i
            idx(index) = sub2ind([n n],j,i-j+1);
            index = index + 1;
        end
    else
        for j = i:-1:1
            idx(index) = sub2ind([n n],j,i-j+1);
            index = index + 1;
        end
    end
end
for i = 2:n
    if mod(i,2) == 1
        for j = i:n
            idx(index) = sub2ind([n n],j,n+i-j);
            index = index + 1;
        end
    else
        for j = n:-1:i
            idx(index) = sub2ind([n n],j,n+i-j);
            index = index + 1;
        end
    end
end

% Display the index array
disp(idx);
